//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiDialogsBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recom_Items
    {
        public int Id { get; set; }
        public Nullable<long> Account_No { get; set; }
        public string Recommended_Items { get; set; }
    }
}
